### ISSUE TITLE
If the main class is named as "Game" with the "Game" template than the class has cyclic dependency.

### ISSUE THREAD

**Issue by SonicGDX** [libgdx/gdx-liftoff#149]
It's a very minor bug but if the main class is the same name as what it is extending there will be a cyclic dependency error. Not sure if this would be feasible /justifiable to put the effort into preventing this since it is obvious how to solve it (just write the full path for the class that it extends) but just thought I'd report this anyway.

**Comment by tommyettinger** [comment]
It's a fair point... I'm not sure how it could be solved in Liftoff code itself, since the template that's selected would affect what main class names are allowed. I think using the name of any core libGDX class for the main class name is a bad idea, though. Just like I wouldn't name a class in my code after something that exists in the core JDK library, like Array, I mean, Queue, I mean, Vector, I mean... uh...

**Comment by cartesian-plane** [comment]
> It's a fair point... I'm not sure how it could be solved in Liftoff code itself, since the template that's selected would affect what main class names are allowed. I think using the name of any core libGDX class for the main class name is a bad idea, though. Just like I wouldn't name a class in my code after something that exists in the core JDK library, like Array, I mean, Queue, I mean, Vector, I mean... uh...

I would like to make a more general fix for this, but I'm not sure if there is any way to read what Template is selected.
Is that not possible, or am I missing something?
