### ISSUE TITLE
DANGEROUS BUG: specifying ~/ as path results in a literal folder "~" being created

### ISSUE THREAD

**Issue by spaceunifyfifty** [libgdx/gdx-liftoff#154]
On MacOS.

If you manually enter a path for your project destination beginning with the unix shortcut for user home directory, i.e `~/libktx-game`, it will create the game folder at `~/~/libktx-game` instead of `~/libktx-game`, which makes removing that folder `~` via `rm` extremely dangerous. I imagine the source of the bug is it interpreting `~` as a literal character for the folder name instead of resolving it as a shortcut for `/Users/USER/`.

# Reproduce
## 1. manually specify a path

<img width="603" alt="image" src="https://github.com/libgdx/gdx-liftoff/assets/158013953/5e0c037d-617f-43e8-9f39-a2ac94fc8de4">

## 2. click "Create folder"

<img width="603" alt="image" src="https://github.com/libgdx/gdx-liftoff/assets/158013953/07f92af4-d515-45d4-a58e-34df9def9619">

## 3. click generate project

<img width="603" alt="image" src="https://github.com/libgdx/gdx-liftoff/assets/158013953/e993c3c9-91af-49ad-8a80-0d21a30ad994">

## 4. observe that there is now a `~/~/libktx-game` folder
```sh
cd ~/
cd "~/"
cd libktx-game/
pwd # ~/~/libktx-game/
```
# This is extremely dangerous
after noticing the erroneous file location, I instinctively went to remove it via `rm -rf ~/`, only realizing immediately after pressing enter that this would remove my entire home directory `Users/USER/`, instead of the "~" folder in `Users/USER/~`.  Fortunately, I don't see anything missing in my home folder. I am not sure why the command failed; my user has sudo privileges, and I saw no output after running the command. Perhaps the command was partially successful and I will soon find dozens of deeply nested and important files gone (I hope not)...

Very close call, this should be patched ASAP.

**Comment by tommyettinger** [comment]
As reiterated by various users across the libGDX Discord, where you (a guest user here) posted as `WarioStrikes`, acted rudely, and then deleted all of your posts, this isn't actually a bug with Liftoff. You also had claimed that you were on Linux there, and now you're saying MacOS, which calls the rest of this into doubt. First, you are making an assumption that all tools on all OSes act like, for instance, Bash does, and replace the path `~` with the absolute path to the user home directory. On Windows, and as you just found out, on MacOS (as well as Linux), a folder can have the name `~`, and if you create a folder with that name you need to be able to delete that folder like any other. That means deleting it using an escaped filename, like you would with a path containing spaces. Liftoff allows creating projects with spaces in the path, of course.

Second, and also as stated a few times on Discord, other major languages don't act like Bash does; Python 3, for instance, allows creating a folder called `~` that is distinct from the user home folder, and the syntax for a folder `~` refers to a relative path to a folder named `~`, not the user home directory. "Other major languages" includes Java, also, so you might want to direct your issue towards OpenJDK, which doesn't use GitHub to track issues anyway ([they use JIRA](https://bugs.openjdk.org/secure/Dashboard.jspa)). I'm curious what they think, since this is presumably a long-standing behavior.

On UNIX, when using the command line, you should be *keenly aware* that any command can have consequences if you aren't conscious of what you are doing. If you are by default in super-user mode, which *no professional would ever recommend* and I hope you weren't doing, then you must by *even more keenly aware* that the consequences can be worse. If you actually were on MacOS, then you absolutely had access to an excellent GUI for the filesystem. You can delete folders there, too.

The bug here is that you even considered entering an `rm -rf` command without checking what you were deleting first. At some point we just need to hold ourselves personally accountable when we make mistakes.

![batman-we-fall-so-we-can-learn-to-pick-ourselves-up](https://github.com/libgdx/gdx-liftoff/assets/160684/b83bf355-69c4-43dc-8874-11ff4f5225cc)
