### ISSUE TITLE
Full paths no longer displays in full

### ISSUE THREAD

**Issue by JojoIce** [libgdx/gdx-liftoff#164]
In general really nice change of the GUI, but one drawback compared to the old style is that the "project path" and the "android SDK" path on last page can no longer be seen in full, they just end with 2(!) and 3 dots if the path is of any length. Before I could see the whole path. Only minor usability but maybe reducing the font size in those fields and/or display the path on a new line full page with could be an easy fix. Making the window wider will not allow me to see the full path either since the GUI area does not stretch, same with 3rd party list.

**Comment by tommyettinger** [comment]
I can't reproduce this. At the absolute smallest window size I can make it, my screen looks like this:

![image](https://github.com/libgdx/gdx-liftoff/assets/160684/3f4d82ef-a079-430c-9a7d-278dfd323648)

And a little wider, it looks like this:
![image](https://github.com/libgdx/gdx-liftoff/assets/160684/5e84282d-8b4f-4c1d-9af2-79b5ede0aaf8)

The second one is about 1000px wide, since it's roughly half the width of my 1080p screen. In both cases the path is clickable, and for the extremely-narrow window only the label becomes partly hidden. There are 3 dots there, by the way, it's just that one merges with the bottom line of the 'E'. Because the file path can be extremely long in some cases, I'm not sure if we want the path section to just grow indefinitely. You can always see the path by clicking it.

I don't know if there's an issue with the third-party list; it does shrink if you crush the window to be very narrow (500px?) but expands back to its normal width if you make the window larger.

![image](https://github.com/libgdx/gdx-liftoff/assets/160684/bc578f3a-8188-4a47-9895-084ac745d29d)

**Comment by JojoIce** [comment]
Maybe I was a bit fuzzy in the description. See the screenshot below. Even though the new GUI has huge space (the full screen) it still is not possible to see the full path to the project. It is also not possible to "scroll right" in the path text-field as in the old. Looking at the old GUI that is on top of less than 1/3 of the new GUI it shows the whole path.

So the path cannot be displayed in the text-field, but the window has lots of space and even the "generate" button is further to the right than the text field extends. 

But as I said, just a minor thing, though IMHO a small step back. New GUI shows about 1/3 of the text compared with old. It does not use the screen space (white boxes). For me when testing, I just filled in the new folder name in the old GUI and clicked the create folder button. Now it is a detour to the OS for creating a folder, selecting it and hoping that it was properly selected since it is not reflected in the GUI (new folder was outside textbox for me).

![Screenshot 2024-06-15 at 11 55 01](https://github.com/libgdx/gdx-liftoff/assets/3921475/4602e8f7-ad1d-42dd-9288-17359119b7d0)
