### ISSUE TITLE
Broken setup on Java 11. construo 1.2.0 requires Java 17

### ISSUE THREAD

**Issue by Mek101** [libgdx/gdx-liftoff#189]
I set liftoff to use Java 11, and without adding any 3rd party dependency, using the Core and Desktop platforms with the Bullet and Asheley extensions, the build immediatly fails with

```
> .\gradlew

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lwjgl3'.
> Could not resolve all artifacts for configuration ':lwjgl3:classpath'.
   > Could not resolve io.github.fourlastor:construo:1.2.0.
     Required by:
         project :lwjgl3 > io.github.fourlastor.construo:io.github.fourlastor.construo.gradle.plugin:1.2.0
      > Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.

* Try:
> Run this build using a Java 17 or newer JVM.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4s
```

![immagine](https://github.com/user-attachments/assets/dccbaafd-8eef-49c5-a675-13052430cc91)
![immagine](https://github.com/user-attachments/assets/e5eea984-5b59-47d4-8a96-e30e94216f9c)

(note, the "not empty error in the screenshot it's there because it's the folder where I set up the project with the same configuration)

**Comment by tommyettinger** [comment]
I'm not sure I'd qualify that as broken -- the docs do say you are strongly encouraged to use Java 17, I guess I can change that to "17+ required to build" now. Java 11 is close to 6 years old now, and at least the people in charge of Android think it's safe to require Java 17 JDKs during building.

Note that you can target Java versions as low as 8 with Java 17 JDKs, meaning users can run your game with quite old Java versions and not notice any issues. Java 17 might actually be able to target 7, though I wouldn't recommend it since every platform can handle at least language level 8. API support always varies between platforms, like how Android doesn't support AWT or Swing features from Java 7. 

There are a lot of JDK improvements that apply just from running your game with Java 17 or newer. Performance on some important methods has gotten better, and even simple things like `Math.min()` and `Math.max()` have seen improvements. The generated JavaDocs have gotten much better in versions 9 and up, with continued improvements over time, though this matters more for libraries than applications. The garbage collector(s) have improved and should cause less stuttering, especially if you tell the JVM to use ZGC or Shenandoah GC. Those things apply even when targeting Java language level 8 but running with JDK17 or newer.

I've had to make sure Liftoff works as soon as possible for users who just downloaded Java and unfortunately get the latest Java version possible (unfortunately because Gradle usually takes a few months to become compatible). It's a challenge to do that and ensure everything works on older JDK versions. Especially considering [even Oracle doesn't support Java 11 unless you pay them the highest rate](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).

To make a long story short, just install Java 17! I usually recommend [Liberica OpenJDK from BellSoft](https://bell-sw.com/pages/downloads/#jdk-17-lts) because its installer has very reasonable, working defaults, and the licensing is clearly free (unlike the haze that Oracle's releases are enveloped in). Java 21 will also work. (Though 21 might not work with older projects, such as those generated with gdx-setup last year or something.) Java 22 should work, but I don't think Oracle will support it much longer, so using a recent LTS release should ensure important updates get backported.

**Comment by Mek101** [comment]
> I'm not sure I'd qualify that as broken

Well, the fact that it picks a default option which results in a broken configuration

> Note that you can target Java versions as low as 8 with Java 17 JDK

Uh, that was never clear to me

> To make a long story short, just install Java 17!

Will!

**Comment by tommyettinger** [comment]
Yeah, the Java ecosystem is kinda a mess of different versions... I think one quick solution I might do is to start compiling gdx-liftoff with Java 17 and setting its compatibility to 17 (or higher). This would make the JAR refuse to run with a version 16 or lower JDK, but I can only hope the error message is helpful... If I remember correctly, it usually isn't.

Back to this issue, the default setting of language level 11 isn't what broke your project, it is running on JDK 11. You can use language level 8, 11, 17, or anything in between with a JDK 17 installation. Some newer versions have an annoying warning (that doesn't affect anything) if you target language level 8. That's about the only thing to note regarding incompatibility currently. I'm not entirely sure what Gradle's defaults and Liftoff's config do regarding the `--release` flag, which makes the JAR act exactly like it was compiled by a specific JDK version, and makes it generally quite compatible with that version. I think maybe Gradle has started using `--release` internally when the compatibility is different... I think some of my libraries have dedicated code for releasing on a specific version... Hmmm....

**Comment by Frosty-J** [comment]
> I think one quick solution I might do is to start compiling gdx-liftoff with Java 17 and setting its compatibility to 17 (or higher). This would make the JAR refuse to run with a version 16 or lower JDK

Please don't. There is no guarantee the JRE used to run Liftoff matches the JDK within the IDE.

**Comment by tommyettinger** [comment]
I haven't done that. I have set up the `--release` flag so it should make JARs compatible with the selected JVM version, in the latest commit. It may have worked before this if Gradle did something behind-the-scenes.

**Comment by tommyettinger** [comment]
So, Gradle 8.10 did this in my stead. Java 17 is now required to run Gradle, so you have no excuses to use older Java. As far as I can tell, Gradle 8.10 or later is required to be able to build any Gradle projects if you only have Java 23 installed (and it will be the newest version in less than a month, which means new users will come in with just Java 23 installed, you know the drill). Docs have been updated to mention that you **must** use Java 17 or later. Closing.

**Comment by aquagray** [comment]
Even with java 17+ I'm still getting this error.. any help would be much appreciated!

I also created the project with generic setup, with no lib added, just `java version` changed to 18 at the end of the steps:
<img width="723" alt="Screenshot 2024-09-06 at 7 47 58 AM" src="https://github.com/user-attachments/assets/bf0d5569-529c-40c2-a397-d470ab428264">

Then ensured that IntelliJ is setup with jdk17+
<img width="748" alt="Screenshot 2024-09-06 at 7 50 47 AM" src="https://github.com/user-attachments/assets/01b68847-923e-4746-9f03-b10550f84fc0">
<img width="1012" alt="Screenshot 2024-09-06 at 7 50 59 AM" src="https://github.com/user-attachments/assets/7bee88d7-5bbb-441c-ac86-3a73ddebf18b">

But I'm still getting
```

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':lwjgl3'.
> Could not resolve all artifacts for configuration ':lwjgl3:classpath'.
   > Could not resolve io.github.fourlastor:construo:1.3.0.
     Required by:
         project :lwjgl3 > io.github.fourlastor.construo:io.github.fourlastor.construo.gradle.plugin:1.3.0
      > Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.

* Try:
> Run this build using a Java 17 or newer JVM.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@1a716b9c of type BuildFlowService.Parameters
   > A problem occurred configuring project ':lwjgl3'.
      > Could not resolve all artifacts for configuration ':lwjgl3:classpath'.
         > Could not resolve io.github.fourlastor:construo:1.3.0.
           Required by:
               project :lwjgl3 > io.github.fourlastor.construo:io.github.fourlastor.construo.gradle.plugin:1.3.0
            > Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.

* Try:
> Run this build using a Java 17 or newer JVM.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

CONFIGURE FAILED in 122ms
```

I thought perhaps there's gradle property that also needs to be updated - but gradle property doesn't seem to specify java version:

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx1G
org.gradle.configureondemand=false
kotlinVersion=1.9.22
graalHelperVersion=2.0.1
enableGraalNative=false
gdxVersion=1.12.1
projectVersion=1.0.0
```

I'm not very well-versed in gradle, so any help would be much appreciated!
