### ISSUE TITLE
Cannot import generated project into Intellij IDEA

### ISSUE THREAD

**Issue by TheEntropyShard** [libgdx/gdx-liftoff#197]
I created a project with **core** and **android** targets. My IntelliJ just dont want to import android subproject:

![image](https://github.com/user-attachments/assets/b9f27467-3d6c-4245-82da-ec78540d9e3b)

Am I supposed to open the project in Android Studio?

**Comment by Frosty-J** [comment]
Android Studio is an easy solution, sure. If you do not have the Android plugin installed (File -> Settings -> Plugins) you can try that to get Android support in IDEA.

**Comment by tommyettinger** [comment]
Yeah, you do need Android tools installed to do Android stuff, and Android Studio is probably the best way to get all the tools you might need. Certain (rare) update-related warnings will only be solvable with Android Studio, though "warning" is maybe over-stating it since they're issued by the IDE or IDE plugin, not the compiler. If you continue to have issues after getting the Android tools available, try marking the Android main folder (`android/src/main/`) as a sources root, by right-clicking the folder in IDEA and choosing "Mark Directory As" -> "Sources Root".

**Comment by TheEntropyShard** [comment]
Thank you all for your answers, yeah, I imported the project into Android Studio successfully.
