### ISSUE TITLE
Exception using construo 1.4

### ISSUE THREAD

**Issue by Sesu8642** [libgdx/gdx-liftoff#199]
The recent gdx-liftoff versions upgraded construo to 1.4. However, there seems to be an issue with the Gradle setup and the 1.4 version. With a newly generated project, I'm getting an error running `./gradlew lwjgl3:packageWinX64`:
`NoSuchMethodError: org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry`

I opened an [issue at construo](https://github.com/fourlastor-alexandria/construo/issues/75) and the author suggests that Android plugin shouldn't be applied to the whole project.

**Comment by tommyettinger** [comment]
This has actually already been fixed, there just hasn't been a release yet. Android and GWT plugins are now applied in their own modules, rather than the root. I could probably push a release soon... There's been some good changes lately. I think there's some issues that need to get sorted out with MOE, since it expects some tasks to be run during setup, and nothing else does that.
