### ISSUE TITLE
HTML | Kotlin - not working

### ISSUE THREAD

**Issue by Vladislav-Shesternin** [libgdx/gdx-liftoff#210]
When I create a project for HTML5 and select Kotlin, a src.main.kotlin folder is created, but it doesn't matter because there are no dependencies for Kotlin in build.gradle, so it doesn't work and I have to write only in Java.

**Comment by tommyettinger** [comment]
Hm, yeah, it would be good... If only there were some note where it is relevant in the program already...

![Not reading is not a good reason for an issue.](https://i.imgur.com/1lhreNt.png)

There's not much room for additional description in the platform description page, and that really, really shouldn't be how you make your decision of what to target and how. Read actual wiki articles, tutorials, whatever; one half-line of description is not enough to say that TeaVM supports Java, Kotlin, Scala, and Groovy, but probably not Clojure, and as for other languages like Frege or XTend or something who even knows... We also don't document in the platforms page that Android and iOS only have partial support for all JVM languages, since they don't have AWT or Swing. Seriously, we have a half-line of text, you actually need to choose what to display when making a GUI, and we already quite clearly say it on the languages page, which is the first place where someone might make a decision that breaks compatibility with GWT.

Closing.
