### ISSUE TITLE
liftoff as a Backend Service

### ISSUE THREAD

**Issue by payne911** [libgdx/gdx-liftoff#25]
With the possible introduction of a new setup tool as a WebApp, there has been discussions about the wonders of being able to extract the Generator's output.

A draft backend has been proposed, and is only lacking the Generator itself: https://github.com/MrStahlfelge/gdx-setup-backend/blob/master/src/main/java/com/badlogic/gdx/setup/rest/ProjectGeneratorController.java#L45

There has been discussions about what would be the easiest approach to this. There seem to be two main approaches (always taking as an input a list of all the non-default options, and outputting a ZIP):

1. A Headless version which would basically work through the command-line interface. (And then use the [``ProcessBuilder``](https://www.baeldung.com/java-lang-processbuilder-api) to call from within the backend's Service.)
2. An "Adapter" (or "Simulator") that would analyze the ``args`` variable of the entry-point of the program (https://github.com/tommyettinger/gdx-liftoff/blob/master/src/main/kotlin/com/github/czyzby/setup/main.kt#L15) and simulate the interactions of a user with that.

**Comment by tommyettinger** [comment]
Simulating interactions (2.) is not easy and also requires a server that isn't headless (i.e. has graphics drivers, which usually means a higher cost IIRC). The headless version (1.) is in general something liftoff should support if it is to replace gdx-setup, since gdx-setup has a headless version. To be fair, gdx-setup's headless version was almost never used, and it took a long time for anyone to notice that it was broken when MOE was removed from the gdx-setup GUI. I'll look into what it would take to get a command-line version working.

**Comment by payne911** [comment]
I forgot I had opened this ticket.

I'm currently working extracting liftoff's logic into a stand-alone repo which will be usable by any consumer.

https://github.com/payne911/gdx-setup-generator

**Comment by tommyettinger** [comment]
This all wound up in a very confusing mixture of projects and didn't end up going anywhere. :( I think I'll close this; there doesn't seem to be much demand from users for this type of feature, and it seems hard to implement.
